# Look docs here https://github.com/asottile/pyupgrade/blob/main/README.md
repos:
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/asottile/pyupgrade
  rev: v3.1.0
  hooks:
    - id: pyupgrade
      args: [--py310-plus]
