# Look docs here https://github.com/asottile/pyupgrade/blob/main/README.md
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
      - id: trailing-whitespace

  # Markdown linter
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.40.0
    hooks:
    - id: markdownlint

  # Dockerfile linter
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.0-beta
    hooks:
      - id: hadolint-docker

  # Pyupgrade is a tool (and pre-commit hook) to automatically upgrade syntax for newer versions of the language
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py312-plus]

  # isort your imports, so you don't have to.
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  # Black is the uncompromising Python code formatter. "Any color you like"
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--skip-string-normalization", "--line-length", "79"]

  # Mypy is a static type checker for Python
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        exclude: src/learning|test-tasks

  # Flake8 is a wrapper around these tools:
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - wemake-python-styleguide
          - flake8-pytest-style
          - flake8-aaa
