services:
  rust:
    image: rust
    container_name: rust
    build:
      context: .
    volumes:
      - ./:/usr/app/
      # both are for zed remote
      #      - ~/.ssh/:/root/.ssh/:ro
      #      - ~/.config/zed:/root/.config/zed:ro
      
      # for zed remote
      # ports:
      # - "2222:22"

# fof zed `docker compose build && docker compose up rust`
