services:
  devc:
    image: devc
    build:
      context: .
    environment:
      AWS_PROFILE: ${AWS_PROFILE}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    volumes:
      - ~/.config/gcloud/:/app/.config/gcloud/
      - ~/.aws:/app/.aws
      - ${CODE_DIR}:/app/code:ro
