---
  - name: Common apps installation
    homebrew_cask:
      name:
        - deepl
#        - avira-antivirus
#        - browserosaurus
        - deepl
        - hiddenbar
        - monitorcontrol
        - signal
        - spotify
        - sublime-text
        - telegram
        - webtorrent

    - name: Install apps from App store
