services:
  python:
    container_name: python_console
    image: python_skatromb
    build:
      context: .
    volumes:
      - /Users/skatromb/Documents/Work/Fishbrain/Tasks:/Users/skatromb/Documents/Work/Fishbrain/Tasks
      - /Users/skatromb/Library/Application Support/JetBrains/PyCharm2022.2/scratches:/Users/skatromb/Library/Application Support/JetBrains/PyCharm2022.2/scratches
      - /Users/skatromb/code:/Users/skatromb/code
