services:
  python:
    container_name: python_skatromb
    image: python_skatromb
    build:
      context: .
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_TABLE: ${DB_TABLE}
    volumes:
      - /Users/skatromb/Documents/Work/Fishbrain/Tasks:/Users/skatromb/Documents/Work/Fishbrain/Tasks
      - /Users/skatromb/Library/Application Support/JetBrains/PyCharm2022.2/scratches:/Users/skatromb/Library/Application Support/JetBrains/PyCharm2022.2/scratches
      - /Users/skatromb/code:/Users/skatromb/code
    ports:
      - 4040:4040
